---
title: "Relatório de Óbitos por Paraquat"
output: html_document
date: "2026-07-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r carregar dados}
library(dplyr)
library(janitor)
library(lubridate)
library(tidyr)
library(readxl)
library(ggplot2)
library(kableExtra)

# CARREGAR BANCO DE DADOS ORIGINAL ----------------------------------------

df <- read.csv2("Banco_original/03_df_paraquat_ajustado.csv")
df <- df |> filter(EVOLUCAO=="Obito por intoxicacao exogena")
```

```{r freqTempo}
# FREQUENCIAS TEMPO -------------------------------------------------------
# Ano
freqAno <- df %>% group_by(NU_ANO) %>% 
  summarise(N = n())

# Mes
freqMes <- df %>% group_by(MES_IS) %>% 
  summarise(N = n())

# Matriz Ano/Mes
freqAnoMes <- df %>% group_by(NU_ANO, MES_IS) %>% 
  summarise(N = n())
```


## EXPOSIÇÕES NO PERÍODO

```{r graf_tempo}
# Ano
freqAno %>% 
  ggplot(aes(x = factor(NU_ANO), y = N))+
  geom_col(fill = 'firebrick3')+
  geom_text(aes(label = N), 
            vjust = -0.5,       # Posiciona o texto um pouco acima da barra
            size = 3.5,         # Tamanho da fonte do rótulo
            color = "black") + 
  labs(x=NULL,
       subtitle = "Casos x Ano",
       y="Registros",
       fill='')+
    theme_bw()




# Mes
freqMes %>% 
  ggplot(aes(x = MES_IS, y = N))+
  geom_col(fill = 'firebrick3')+
  geom_text(aes(label = N), 
            vjust = -0.5,       # Posiciona o texto um pouco acima da barra
            size = 3.5,         # Tamanho da fonte do rótulo
            color = "black") +
  labs(x=NULL,
       subtitle = "\n\n Casos x Mês",
       y="Registros")+
  theme_bw()
```

## REGIÃO, ESTADO E MUNICÍPIO DA EXPOSIÇÃO

```{r regiao}
# REGIAO, ESTADO E MUNICIPIO DA EXPOSICAO --------------------------------------
## Casos
# Regiao
df %>% 
  group_by(REGIAO) %>% 
  summarise(N = n()) %>% 
  #na.omit() %>% 
  arrange(desc(N)) %>% kable(caption = "Região") |> kable_classic()

#Estado
df %>% 
  group_by(SG_UF) %>% 
  summarise(N = n()) %>% 
  #na.omit() %>% 
  arrange(desc(N)) %>% head(28) %>% kable(caption = "\n\n Estado") |> kable_classic()

# Município
df %>% 
  group_by(SG_UF, NOME_MUNI) %>% 
  summarise(N = n()) %>% 
  #na.omit() %>% 
  arrange(desc(N)) %>% head(20)%>% kable(caption = "\n\n Município") |> kable_classic()
```


## SOCIODEMOGRÁFICOS

```{r socio}
cat("Idade em anos:\n")
print(summary(df$IDADE))

# Faixa etaria
faixaEtaria <- tabyl(dat = df,
                     var1 = FAIXA_ETARIA,
                     var2 = CS_SEXO) %>% 
  adorn_totals(where = "col") |> kable(caption = "\n\n") |> kable_classic(); faixaEtaria

# Raça
raca <- tabyl(dat = df,
              var1 = CS_RACA,
              var2 = CS_SEXO) %>% 
  adorn_totals(where = "col") |> kable(caption = "\n\n") |> kable_classic(); raca

# Gestação
gestacao <- tabyl(dat = df,
              var1 = CS_GESTANT,
              var2 = CS_SEXO) %>% 
  adorn_totals(where = "col") |> kable(caption = "\n\n") |> kable_classic(); gestacao

# Escolaridade
escolaridade <- tabyl(dat = df,
                  var1 = CS_ESCOL_N,
                  var2 = CS_SEXO) %>% 
  adorn_totals(where = "col") |> kable(caption = "\n\n") |> kable_classic(); escolaridade
```


## EXPOSIÇÃO

```{r exposicao}
# Local da exposição
local_exposicao <- tabyl(dat = df,
                      var1 = LOC_EXPO,
                      var2 = CS_SEXO, 
                      show_na = TRUE, 
                      show_missing_levels = TRUE) %>% 
  adorn_totals(where = "col")|> kable(caption = "\n\n") |> kable_classic(); local_exposicao

# Grupo do agente toxico
agente_tox <- tabyl(dat = df,
                         var1 = AGENTE_TOX,
                         var2 = CS_SEXO, 
                         show_na = TRUE, 
                         show_missing_levels = TRUE) %>% 
  adorn_totals(where = "col")|> kable(caption = "\n\n") |> kable_classic(); agente_tox

# Via de exposicao (se Agrotoxico)
## Via 1
via_expo1 <- tabyl(dat = df[df$AGENTE_TOX %in% c('Agrotoxico agricola',
                                                'Agrotoxico domestico',
                                                'Agrotoxico spublica'),],
                         var1 = VIA_1,
                         var2 = CS_SEXO, 
                         show_na = TRUE, 
                         show_missing_levels = TRUE) %>% 
  adorn_totals(where = "col")|> kable(caption = "\n\n") |> kable_classic(); via_expo1

## Via 2
via_expo2 <- tabyl(dat = df[df$AGENTE_TOX %in% c('Agrotoxico agricola',
                                                 'Agrotoxico domestico',
                                                 'Agrotoxico spublica'),],
                   var1 = VIA_2,
                   var2 = CS_SEXO, 
                   show_na = TRUE, 
                   show_missing_levels = TRUE) %>% 
  adorn_totals(where = "col")|> kable(caption = "\n\n") |> kable_classic(); via_expo2

## Via 3
via_expo3 <- tabyl(dat = df[df$AGENTE_TOX %in% c('Agrotoxico agricola',
                                                 'Agrotoxico domestico',
                                                 'Agrotoxico spublica'),],
                   var1 = VIA_3,
                   var2 = CS_SEXO, 
                   show_na = TRUE, 
                   show_missing_levels = TRUE) %>% 
  adorn_totals(where = "col")|> kable(caption = "\n\n") |> kable_classic(); via_expo3


# Circunstancia de exposicao
circunstancia <- tabyl(dat = df,
                       var1 = CIRCUNSTAN,
                       var2 = CS_SEXO, 
                       show_na = TRUE, 
                       show_missing_levels = TRUE) %>% 
  adorn_totals(where = "col")|> kable(caption = "\n\n") |> kable_classic(); circunstancia


# Exposicao no trabalho
expo_trabalho <- tabyl(dat = df,
                       var1 = DOENCA_TRA,
                       var2 = CS_SEXO, 
                       show_na = TRUE, 
                       show_missing_levels = TRUE) %>% 
  adorn_totals(where = "col")|> kable(caption = "\n\n") |> kable_classic(); expo_trabalho

# Tipo exposicao
tipo_expo <- tabyl(dat = df,
                   var1 = TPEXP,
                   var2 = CS_SEXO, 
                   show_na = TRUE, 
                   show_missing_levels = TRUE) %>% 
  adorn_totals(where = "col")|> kable(caption = "\n\n") |> kable_classic(); tipo_expo

```

## CLASSIFICAÇÃO

```{r classificacao}
# Classificacao
classificacao <- tabyl(dat = df,
                   var1 = CLASSI_FIN,
                   var2 = CS_SEXO, 
                   show_na = TRUE, 
                   show_missing_levels = TRUE) %>% 
  adorn_totals(where = "col") |> kable(caption = "\n\n") |> kable_classic(); classificacao

# Criterio confirmacao
criterio <- tabyl(dat = df,
                     var1 = CRITERIO,
                     var2 = CS_SEXO, 
                     show_na = TRUE, 
                     show_missing_levels = TRUE) %>% 
  adorn_totals(where = "col") |> kable(caption = "\n\n") |> kable_classic(); criterio

# Evolucao
evolucao <- tabyl(dat = df,
                  var1 = EVOLUCAO,
                  var2 = CS_SEXO, 
                  show_na = TRUE, 
                  show_missing_levels = TRUE) |> kable(caption = "\n\n") |> kable_classic(); evolucao
```

